//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitPlus.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitPlus.Assets.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  (Auto Fetch) 的本地化字符串。
        /// </summary>
        internal static string AutoFetchToolTipSuffix {
            get {
                return ResourceManager.GetString("AutoFetchToolTipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching status... 的本地化字符串。
        /// </summary>
        internal static string FetchingStatus {
            get {
                return ResourceManager.GetString("FetchingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to fetch status: {0} 的本地化字符串。
        /// </summary>
        internal static string FetchStatusFailed {
            get {
                return ResourceManager.GetString("FetchStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable files (*.exe)|*.exe|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string FileBrowser_ExecutableFilter {
            get {
                return ResourceManager.GetString("FileBrowser_ExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select git.exe 的本地化字符串。
        /// </summary>
        internal static string FileBrowser_SelectGitTitle {
            get {
                return ResourceManager.GetString("FileBrowser_SelectGitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Conventional Commit Template 的本地化字符串。
        /// </summary>
        internal static string InsertConventionalCommitToolTip {
            get {
                return ResourceManager.GetString("InsertConventionalCommitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes between automatic git fetch calls. Minimum: 1. 的本地化字符串。
        /// </summary>
        internal static string Option_AutoFetchIntervalMinutes_Description {
            get {
                return ResourceManager.GetString("Option_AutoFetchIntervalMinutes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetch Interval (minutes) 的本地化字符串。
        /// </summary>
        internal static string Option_AutoFetchIntervalMinutes_DisplayName {
            get {
                return ResourceManager.GetString("Option_AutoFetchIntervalMinutes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines whether to show the auto pull button in the toolbar. 的本地化字符串。
        /// </summary>
        internal static string Option_AutoPullVisible_Description {
            get {
                return ResourceManager.GetString("Option_AutoPullVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Auto Pull Button 的本地化字符串。
        /// </summary>
        internal static string Option_AutoPullVisible_DisplayName {
            get {
                return ResourceManager.GetString("Option_AutoPullVisible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines the file name for conventional commit message scopes. (Use the menu item &apos;Generate Scope Template&apos; to generate the template file) 的本地化字符串。
        /// </summary>
        internal static string Option_ConventionalCommitScopeFileName_Description {
            get {
                return ResourceManager.GetString("Option_ConventionalCommitScopeFileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conventional Commit Scope File Name 的本地化字符串。
        /// </summary>
        internal static string Option_ConventionalCommitScopeFileName_DisplayName {
            get {
                return ResourceManager.GetString("Option_ConventionalCommitScopeFileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines whether to show the conventional commits button in the toolbar. 的本地化字符串。
        /// </summary>
        internal static string Option_ConventionalCommitsVisible_Description {
            get {
                return ResourceManager.GetString("Option_ConventionalCommitsVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Conventional Commits Button 的本地化字符串。
        /// </summary>
        internal static string Option_ConventionalCommitsVisible_DisplayName {
            get {
                return ResourceManager.GetString("Option_ConventionalCommitsVisible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to git.exe. Leave empty to use the system PATH. 的本地化字符串。
        /// </summary>
        internal static string Option_GitFileName_Description {
            get {
                return ResourceManager.GetString("Option_GitFileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git File Path 的本地化字符串。
        /// </summary>
        internal static string Option_GitFileName_DisplayName {
            get {
                return ResourceManager.GetString("Option_GitFileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies the log level for GitPlus operations. 的本地化字符串。
        /// </summary>
        internal static string Option_LogLevel_Description {
            get {
                return ResourceManager.GetString("Option_LogLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level 的本地化字符串。
        /// </summary>
        internal static string Option_LogLevel_DisplayName {
            get {
                return ResourceManager.GetString("Option_LogLevel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout for Git operations in seconds. Minimum: 1. 的本地化字符串。
        /// </summary>
        internal static string Option_TimeoutSeconds_Description {
            get {
                return ResourceManager.GetString("Option_TimeoutSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout (seconds) 的本地化字符串。
        /// </summary>
        internal static string Option_TimeoutSeconds_DisplayName {
            get {
                return ResourceManager.GetString("Option_TimeoutSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, periodically runs git fetch --all --prune in the background. 的本地化字符串。
        /// </summary>
        internal static string Option_UseAutoFetch_Description {
            get {
                return ResourceManager.GetString("Option_UseAutoFetch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Auto Fetch 的本地化字符串。
        /// </summary>
        internal static string Option_UseAutoFetch_DisplayName {
            get {
                return ResourceManager.GetString("Option_UseAutoFetch_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines whether to use scope in commit messages. 的本地化字符串。
        /// </summary>
        internal static string Option_UseConventionalCommitScope_Description {
            get {
                return ResourceManager.GetString("Option_UseConventionalCommitScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Scope 的本地化字符串。
        /// </summary>
        internal static string Option_UseConventionalCommitScope_DisplayName {
            get {
                return ResourceManager.GetString("Option_UseConventionalCommitScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, git pull uses --rebase instead of --ff-only. 的本地化字符串。
        /// </summary>
        internal static string Option_UseRebase_Description {
            get {
                return ResourceManager.GetString("Option_UseRebase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Rebase on Pull 的本地化字符串。
        /// </summary>
        internal static string Option_UseRebase_DisplayName {
            get {
                return ResourceManager.GetString("Option_UseRebase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Fetch 的本地化字符串。
        /// </summary>
        internal static string OptionCategory_Auto_Fetch {
            get {
                return ResourceManager.GetString("OptionCategory_Auto_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit 的本地化字符串。
        /// </summary>
        internal static string OptionCategory_Commit {
            get {
                return ResourceManager.GetString("OptionCategory_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string OptionCategory_General {
            get {
                return ResourceManager.GetString("OptionCategory_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        internal static string OptionCategory_Logging {
            get {
                return ResourceManager.GetString("OptionCategory_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull 的本地化字符串。
        /// </summary>
        internal static string OptionCategory_Pull {
            get {
                return ResourceManager.GetString("OptionCategory_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull failed: {0} 的本地化字符串。
        /// </summary>
        internal static string PullFailed {
            get {
                return ResourceManager.GetString("PullFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pulling... 的本地化字符串。
        /// </summary>
        internal static string Pulling {
            get {
                return ResourceManager.GetString("Pulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull (Auto Stash) 的本地化字符串。
        /// </summary>
        internal static string PullWithStashToolTip {
            get {
                return ResourceManager.GetString("PullWithStashToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restoring stash... 的本地化字符串。
        /// </summary>
        internal static string RestoringStash {
            get {
                return ResourceManager.GetString("RestoringStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scopes file already exists. Please delete it first if you want to regenerate. 的本地化字符串。
        /// </summary>
        internal static string ScopesFileExistsMessage {
            get {
                return ResourceManager.GetString("ScopesFileExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scopes File Exists 的本地化字符串。
        /// </summary>
        internal static string ScopesFileExistsTitle {
            get {
                return ResourceManager.GetString("ScopesFileExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stash failed: {0} 的本地化字符串。
        /// </summary>
        internal static string StashFailed {
            get {
                return ResourceManager.GetString("StashFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stashing changes... 的本地化字符串。
        /// </summary>
        internal static string StashingChanges {
            get {
                return ResourceManager.GetString("StashingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stash pop failed: {0} 的本地化字符串。
        /// </summary>
        internal static string StashPopFailed {
            get {
                return ResourceManager.GetString("StashPopFailed", resourceCulture);
            }
        }
    }
}
